# Generated by Django 4.1 on 2022-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('degree', models.CharField(max_length=50)),
                ('gradYear', models.IntegerField()),
            ],
        ),
    ]
